* 1923
** About
Magnificient card game.

*** Testimonials
"1923 saved my life." - Local man

"So asynchronous!" - Carlos

"Surprisingly fun." - Holly


** Rules
*** Players
2 or more players are required to play

**** Decks
The number of decks used depend on the number of players. To
calculate how many decks you should be using, here is a handy-dandy
equation:

number of decks = ceil( number of players / 3 )

On the other hand, if you lack the proper amount of decks, just go
with what you got. 

*** Gameplay

**** Winning
Combined card value (blackjack rules; Ace can be 1 or 11) between
19-23. If multiple players are within that range, the player with the
value closest to 23 wins. If no player is within that range, the
player with the value closest to 19 or 23 wins (being closer to 19 or
23 are equal). Winning player keeps all cards from the round
(including tiebreaker cards). 

***** Breaking Ties
Player with the highest average card value wins. If multiple players
have the same average card value, the players will draw a single card
and highest card (as before, based on value, i.e. 10 is the same as a
king) wins (repeat until winner is found).

**** Drawing Cards
1. Every player draws 2 cards and places them face down (without
   looking at them). By custom, the cards are to be placed
   side-by-side and to the right hand side in front of the player.
2. Players may look at one of their 2 cards.
3. If a player desires to view the other card, they may due so, but
   are required to take another card from the deck as a result.
   Players can repeat this step as many times as they would like. This
   is done asynchronously (i.e., you needn't wait and see what other
   players do). By custom, each additional card must be placed to the
   left of the original 2 cards (and so on).
3. Each player must lock their left-most card when they are done
   drawing cards (i.e., the card they do not know the value of). Once
   a player has locked, they cannot unlock. To lock, the player turns
   the card sideways -- a card is locked once the player has removed
   their hand from the card. 
4. Once each player has locked, all players must turnover their cards
   (from right to left) and count their value. Winner is determined as
   outlined above.


*** Winning
When there aren't enough cards left to carry out another round, the
game is over. What does it mean there aren't enough cards? First, if
there enough cards for every player to have at least 2, then there
are enough cards. Any remaining cards after every player has taken 2
are availible in a first come-first serve fashion. If there are only
enough cards for 1 card per player, then the gameplay reverts to war.
In all other cases, there aren't enough cards, and the remaining
cards are dead.

The winner is the player with the most cards.


** Creators
- Thomas Donahue
- Carlos Asmat
- Cody Canning
